<?xml version="1.0" encoding="utf-8"?>
<Database Name="heavenlydata01" EntityNamespace="Auth" Class="AuthDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.UserRoles" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="RoleID" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="UserRole_UserRoleMapping" Member="UserRoleMappings" ThisKey="RoleID" OtherKey="UserRoleID" Type="UserRoleMapping" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="Char(60) NOT NULL" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_UserRoleMapping" Member="UserRoleMappings" ThisKey="UserID" OtherKey="UserID" Type="UserRoleMapping" />
    </Type>
  </Table>
  <Table Name="dbo.UserRoleMappings" Member="UserRoleMappings">
    <Type Name="UserRoleMapping">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserRoleID" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="UserRole_UserRoleMapping" Member="UserRole" ThisKey="UserRoleID" OtherKey="RoleID" Type="UserRole" IsForeignKey="true" />
      <Association Name="User_UserRoleMapping" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>